
import { SoraScript } from "../types";

export const uploadToYouTube = async (
  script: SoraScript, 
  videoBlob: Blob, 
  accessToken: string,
  publishAt: Date
): Promise<string> => {
  // 1. 初始化上傳 (Resumable Upload)
  const metadata = {
    snippet: {
      title: script.title.substring(0, 100), // YouTube 標題限制 100 字
      description: `${script.videoDescription}\n\nTags: ${script.videoTags.join(', ')}\n\nGenerated by Sora 2 Architect`,
      tags: script.videoTags,
      categoryId: "22" // People & Blogs
    },
    status: {
      privacyStatus: "private", // 排程發布必須先設為 private
      publishAt: publishAt.toISOString() // 設定發布時間
    }
  };

  const initResponse = await fetch("https://www.googleapis.com/upload/youtube/v3/videos?uploadType=resumable&part=snippet,status", {
    method: "POST",
    headers: {
      "Authorization": `Bearer ${accessToken}`,
      "Content-Type": "application/json",
      "X-Upload-Content-Length": videoBlob.size.toString(),
      "X-Upload-Content-Type": "video/mp4"
    },
    body: JSON.stringify(metadata)
  });

  if (!initResponse.ok) {
    const errText = await initResponse.text();
    throw new Error(`YouTube 初始化失敗: ${initResponse.status} ${errText}`);
  }

  const uploadUrl = initResponse.headers.get("Location");
  if (!uploadUrl) throw new Error("未取得上傳網址 (Location Header missing)");

  // 2. 上傳影片二進位資料
  const uploadResponse = await fetch(uploadUrl, {
    method: "PUT",
    headers: {
      "Content-Type": "video/mp4"
    },
    body: videoBlob
  });

  if (!uploadResponse.ok) {
    throw new Error("影片資料傳輸失敗");
  }

  const result = await uploadResponse.json();
  return result.id;
};
